### ISSUE TITLE
加上License

### ISSUE THREAD

**Issue by winxpqq955** [SuperSkidder/OpenHanabi#2]
[https://docs.github.com/cn/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository](https://docs.github.com/cn/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository)

>您没有选择许可的义务， 但如果没有许可，就会默认实施版权法，因此您会保留对您的源代码的所有权利，任何人都不能复制、分发您的工作或创建其派生作品。 如果您创建开源项目，强烈建议您包含开源许可。

**Comment by Bannyfelt13** [comment]
@SuperSkidder

**Comment by kotonemywaifu** [comment]
**\*** 你知道吗： 中国不承认「数字千年版权法」

**Comment by winxpqq955** [comment]
> ***** 你知道吗： 中国不承认「数字千年版权法」

Except to the extent applicable law provides otherwise, this Agreement between you and GitHub and any access to or use of the Website or the Service are governed by the federal laws of _the United States of America and the laws of the State of California_, without regard to conflict of law provisions. You and GitHub agree to submit to the exclusive jurisdiction and venue of the courts located in the City and County of San Francisco, California.

**Comment by winxpqq955** [comment]
> ***** 你知道吗： 中国不承认「数字千年版权法」

以及，没有许可的仓库就是all rights reserved
适用伯尔尼公约
[Berne Convention](https://en.wikipedia.org/wiki/Berne_Convention)

**Comment by hax0r31337** [comment]
> > ***** 你知道吗： 中国不承认「数字千年版权法」
> 
> 以及，没有许可的仓库就是all rights reserved 适用伯尔尼公约 [Berne Convention](https://en.wikipedia.org/wiki/Berne_Convention)

然后呢... 和 「中国不承认美国的版权法案有什么关系」

**Comment by SuperSkidder** [comment]
This repository now uses the GNU 3.0
